Avoid duplication of `index.md` in `SUMMARY.md`
This fixes the following `mdbook build` error when using mdbook 0.4.48:
Error: Summary parsing failed for file="/tmp/wezterm/docs/./SUMMARY.md"
Caused By: Duplicate file in SUMMARY.md: "index.md"